version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsgvo-checker:latest
    environment:
      - NODE_ENV=production
      - PORT=5174
      - STATIC_DIR=/app/backend/public
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    restart: unless-stopped
    networks:
      - web

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
